### ISSUE TITLE
[Enhancement] Helmet Cameras as Radar Upgrade

### ISSUE THREAD

**Issue by ZenithRogue** [The0therOne/Helmet_Cameras#26]
Helmet cameras are a really cool concept, although with my group's playstyle we would prefer it to be a purchasable ship/radar upgrade.

Would you be able to add a configuration option to allow for this?

**Comment by The0therOne** [comment]
Hi! Thanks for your feedback.
I dont plan to add it as upgrade, because it will change mod from client side to server side. A lot of players prefer client side mods and dont want this function. Sorry for that.
Maybe later, when i will have enough time for that, i can try to add it with config option (if true, is server side with upgrade, if false, is client side without upgrade).
