### ISSUE TITLE
Lag with more than 4 players

### ISSUE THREAD

**Issue by DeCat4** [The0therOne/Helmet_Cameras#30]
can there be an option to limit how many people are loaded at once? in servers with more than 10 players standing in the ship is extremely laggy and i figured helmet cameras renders all cameras at once, perhaps make it so you can set a limit of how many players are rendered at once so for example if i set it to 5 the camera of the current player i'm watching is rendered and the cameras of the 4 next players according to the switch camera button.

**Comment by The0therOne** [comment]
Hi. I really cant understand, why it is so laggy for some players.
I just use 1 camera and change position of it between players.
Anyway, I dont want update this mod. It was just a little interesting project for me. However, thanks for using it!

**Comment by KarmyDev** [comment]
@The0therOne After taking a peek at your code, I found that you use `GameObject.Find` to access CameraMonitorScript,
using Find is very inefficient operation, and executing it every frame makes script search entire hierarchy of objects for that object. 
https://github.com/The0therOne/Helmet_Cameras/blob/6a4b73a6d82e94f6f3a041f7db04ff3b35b0859f/HelmetCamera/HelmetCamera.cs#L163

Possibly that's the culprit, I'd suggest you cache the object that you are using in the script.
```cs
GameObject cameraMonitorScriptObjectReference = null;

void Update()
{
	// ..., line 163
	if (cameraMonitorScriptObjectReference == null)
	{
		// Find camera monitor script only once and cache it
		cameraMonitorScriptObjectReference = GameObject.Find("Environment/HangarShip/ShipModels2b/MonitorWall/Cube.001/CameraMonitorScript");
	}
	// further use cameraMonitorScriptObjectReference variable instead of fetching it every frame
}             
```
Similar things can be applied for other `Transform.Find` but it depends on how much things you have to handle, either way I propose using chain of [`Transform.GetChild(int index);`](https://docs.unity3d.com/ScriptReference/Transform.GetChild.html) calls, to get to the wanted object.

You can use UnityExplorer to view the hierarchy of in-game scene.

For instance:
```cs
// line 170
transformAndName.transform.Find("ScavengerModel/metarig/CameraContainer/MainCamera/HelmetLights").position
```
can be replaced by
```cs
// References object: "ScavengerModel/metarig/CameraContainer/MainCamera/HelmetLights"
transformAndName.transform.GetChild(0).GetChild(3).GetChild(3).GetChild(0).GetChild(3).position
```

A little neat thing you could do, is use `System.Linq.Where()` instead of using for loop for finding dead body of player.
```cs
DeadBodyInfo deadBody = UnityEngine.Object.FindObjectsOfType<DeadBodyInfo>().Where(player => player.playerScript.playerUsername == transformAndName.name);
```

Anyway personally I'd probably write this differently. 
Hook up to the Spawning/Despawning methods and cache references to camera placements for each player by their internal ID, then use that to reference them for setting position of body camera
But for now these are proposal fixes that should make mod perform a little better

I could suggest a PR fixing this issue, however your repository doesn't have a license, which prevents me from contributing to the code

**Comment by The0therOne** [comment]
Hi!
Thanks for your comment! Seems like you very experienced with c# and unity :) 
Added license. If you want you can try to make PR.
